const constants = {
  ADD_MOVIE: 'ADD_MOVIE',
  CLEAR_MOVIES: 'CLEAR_MOVIES',
  SET_FETCHING: 'SET_FETCHING',
  CLEAR_FETCHING: 'CLEAR_FETCHING',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SET_QUERY: 'SET_QUERY'
};

export default constants;